services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=PROJECT_PHP
      - MYSQL_USER=jayp
      - MYSQL_PASSWORD=jayp
    ports:
      - 3307:3306